Run the tests in the pre-commit hook.
The test target is expected to exit with non-zero status on failure

see http://blog.securemacprogramming.com/2013/11/automated-tests-with-the-gnustep-test-framework/

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -6,4 +6,10 @@ if [ $? != 0 ]; then
     exit 1
 fi
 
+make check
+if [ $? != 0 ]; then
+    echo "Not allowing you to commit, the tests fail."
+    exit 1
+fi
+
 exit 0
